### ISSUE TITLE
only half the rows are parsed out from this TSV

### ISSUE THREAD

**Issue by VladimirAlexiev** [tarql/tarql#45] opened 2015-07-24 15:47 UTC
I downloaded [this file as tsv](https://docs.google.com/spreadsheets/d/14xNJm93CZeZQLrg2qp4nJscVb9oZF5w2oTk0pleEj4c/edit?usp=sharing) and counted rows. Got 670 but the file has 1814 rows.

So then extracted the IDs with this query (UK-TopFoto.tarql):

``` sparql
SELECT ?Filename
FROM <UK-TopFoto-1814.tsv#delimiter=tab>
WHERE {}
```

and this command

``` sh
cut -f1 UK-TopFoto.tsv >a
tarql UK-TopFoto.tarql |perl -ne "print if s{\| \"(.*)\" \|}{$1}" >b
```

Compared a and b and the first missing ID is this row:

EUFD000271  The opening of ' Hinds ' restaurant , Eltham .. 22 February 1936 ..         Eltham  London  United Kingdom England  GBR Twentieth century;Between the wars;black and white;monochrome;Topham;1930s , 30s , nineteen thirties , thirties;20th Century;Europeana Photography;food;Waitress;dinner table;fashion;Man;women;Customers;Dining;Tables;Counter;Eat;Eating;knapkins;Windows;europeana photography;Europeana Food and Drink  General John Topham / TopFoto.co.uk / EUFD  19360222    John Topham / TopFoto.co.uk  / EUFD EU027726    Between The Wars    Glass plate mono negative       John Topham T2793       

But I don't see anything special about it...

**Comment by VladimirAlexiev** [comment] 2015-07-24 15:48
Sorry, I think I posted this to the wrong project. I've now posted it as https://github.com/tarql/tarql/issues/45. I think it should be closed here

**Comment by cygri** [comment] 2016-12-22 20:53
This appears to be caused by the same issue as #50, non-matching quotes.

This does make me question Tarql's behaviour. There is really no reason why a single `"` character in the middle of a field in a TSV file should be interpreted as the beginning of a multi-line field.

Perhaps the expectations for TSV are different than for CSV? CSV needs the ability to put quotes around fields, because commas occur quite frequently in content. TSV doesn't need them as much, because tabs are rare in content. I don't think that a large percentage of TSV files assigns any special meaning to quotes, and I don't think that multi-line fields are really a thing in TSV.

**Comment by VladimirAlexiev** [comment] 2016-12-23 09:34
Agreed!

**Comment by cygri** [comment] 2016-12-23 12:40
Closing this as a duplicate of #10.

**Closed by cygri** 2016-12-23 12:40 UTC
